id = "orbi"
name = "Orbi"
description = "The open source coding agent."
version = "1.2.27"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/orbi"

[agent_servers.orbi]
name = "Orbi"
icon = "./icons/orbi.svg"

[agent_servers.orbi.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/orbi/releases/download/v1.2.27/orbi-darwin-arm64.zip"
cmd = "./orbi"
args = ["acp"]

[agent_servers.orbi.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/orbi/releases/download/v1.2.27/orbi-darwin-x64.zip"
cmd = "./orbi"
args = ["acp"]

[agent_servers.orbi.targets.linux-aarch64]
archive = "https://github.com/anomalyco/orbi/releases/download/v1.2.27/orbi-linux-arm64.tar.gz"
cmd = "./orbi"
args = ["acp"]

[agent_servers.orbi.targets.linux-x86_64]
archive = "https://github.com/anomalyco/orbi/releases/download/v1.2.27/orbi-linux-x64.tar.gz"
cmd = "./orbi"
args = ["acp"]

[agent_servers.orbi.targets.windows-x86_64]
archive = "https://github.com/anomalyco/orbi/releases/download/v1.2.27/orbi-windows-x64.zip"
cmd = "./orbi.exe"
args = ["acp"]
