name: orbi

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  orbi:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /orbi') ||
      startsWith(github.event.comment.body, '/orbi')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run orbi
        uses: anomalyco/orbi/github@latest
        env:
          ORBI_API_KEY: ${{ secrets.ORBI_API_KEY }}
          ORBI_PERMISSION: '{"bash": "deny"}'
        with:
          model: orbi/claude-opus-4-5
